### ISSUE TITLE
Non working gmf example

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#2844]
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/elevation.html
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/drawfeature.html

Error is:
```
Error: [$injector:unpr] http://errors.angularjs.org/1.6.6/$injector/unpr?p0=gmfLayersUrlProvider%20%3C-%20gmfLayersUrl%20%3C-%20gmfEditFeature%20%3C-%20gmfObjectEditingManager%20%3C-%20gmfPermalink
```

**Comment by fredj** [comment]
The `gmfLayersUrl` constant is missing

**Comment by ger-benjamin** [comment]
Please always add a label 'ready' and a milestone for our dashboard

**Comment by pfirpfel** [comment]
Still both broken for me with current master, but they work with 2.2.

Error message:
```
angular.js:14700 Error: [$injector:unpr] Unknown provider: gmfLayersUrlProvider <- gmfLayersUrl <- gmfEditFeature <- gmfObjectEditingManager <- gmfPermalink
http://errors.angularjs.org/1.6.6/$injector/unpr?p0=gmfLayersUrlProvider%20%3C-%20gmfLayersUrl%20%3C-%20gmfEditFeature%20%3C-%20gmfObjectEditingManager%20%3C-%20gmfPermalink
    at angular.js:116
    at angular.js:4826
    at Object.getService [as get] (angular.js:4981)
    at angular.js:4831
    at getService (angular.js:4981)
    at injectionArgs (angular.js:5006)
    at Object.instantiate (angular.js:5052)
    at Object.<anonymous> (angular.js:4889)
    at Object.invoke (angular.js:5040)
    at Object.enforcedReturnValue [as $get] (angular.js:4873)
```

**Comment by pfirpfel** [comment]
Fixed with #3157

**Comment by sbrunner** [comment]
Create :-)
